### ISSUE TITLE
Creating a OCR 

### ISSUE THREAD

**Issue by Xiralv** [doo/scanbot-sdk-example-cordova#1]
Hi eddyfrank love the project that you made... I have some question about the new update.. in scanbot 1.2.0
I wanna try the OCR feature.. I do that by selecting first an image and scan it just like the documentationDetection module.. but nothing happens when I do that.. and where I will put the osd.traineeddata file?

**Comment by eddyfrank** [comment]
Hi @Xiralv,

thanks for your feedback.

Step 1 - Prepare traineddata:
Copy/download the traineddata files into `languageDataPath`: 
- `osd.traineddata`
- `eng.traineddata` (or other language files)
You can get the `languageDataPath` via `getOcrConfigs(..)` method.

Step 2 - Run OCR on image(s):
Use the `performOcr(..)` method by passing an array of image file URIs.

For more details please see the docs: https://scanbotsdk.github.io/documentation/cordova/

We will add OCR demo code into this example app very soon.

Regards,
Eddy
