### ISSUE TITLE
Where to put traineddata files in android application

### ISSUE THREAD

**Issue by phonegap20** [doo/scanbot-sdk-example-cordova#2]
Dear Team,

Thanks for creating a plugin for cordova, it's really productive and a great achievement.
I am trying to implement OCR feature in my cordova app, every time i call getOcrConfigs i don't get language file which i added in application's assets folder.

i am keep getting below error
"Missing OCR language files for languages"

Please suggest me where i have to add .traineddata file in my project to make it working.
Thanks a lot in advance.

Thanks,
Jitendra

**Comment by eddyfrank** [comment]
Hi @phonegap20 ,

thanks for your feedback.

You have to copy the language files into the `languageDataPath` returned by the `getOcrConfigs()` method. A simple solution might be like this: provide the language files via assets in your application bundle and copy them on runtime into the `languageDataPath` directory once.
Or alternatively, if you don't want to put the language files in the app-bundle, you can download them on runtime and place in the `languageDataPath` directory.
Please also don't forget the `osd.traineddata` file.

Regards,
Eddy

**Comment by phonegap20** [comment]
Dear Eddyfrank,
Thanks for quick response.

Scanbot already have some functions to download at runtime or i have to manage it ?
Let's say i want to support english language at the moment, Do i have to put both osd.traineddata and eng.traineddata in languageDataPath ?

Thanks,
Jitendra

**Comment by eddyfrank** [comment]
> Scanbot already have some functions to download at runtime..
No, it's up to you to implement a suitable handling of language files (via app bundle, download, or other approach), since every app has different requirements.

> Let's say i want to support english language at the moment, Do i have to put both 
> osd.traineddata and eng.traineddata in languageDataPath ?
Yes, exactly.

**Comment by phonegap20** [comment]
Hi,

I used getOcrConfigs  to get languageDataPath and it shows below location.
file:///storage/emulated/0/Android/data/com.arttha.orcdemo/files/binaries/tessdata

I moved eng.traineddata file in above path successfully using cordova file plugin but when i get installedLanguages it always show me empty.

Not sure what is the issue, can you suggest please ?

Thanks,
Jitendra

**Comment by eddyfrank** [comment]
Hi Jitendra,

as I said, please don't forget the `osd.traineddata` file. It is important for OCR functionality.
Place it in the same directory where your `eng.traineddata` file is.
Without the `osd.traineddata` file the Scanbot SDK will not accept any language as "installed". That's why you don't see your language in the config results as installed.

Please see our docs: https://scanbotsdk.github.io/documentation/cordova/#ocrLanguages

Regards,
Eddy

**Comment by phonegap20** [comment]
Dear Eddy,

Thanks a lot for helping me.

I will do that and will try again.

Thanks,
Jitendra

**Comment by phonegap20** [comment]
Dear Eddy,
I followed the steps as you suggested and after adding osd.traineddata file i am able to get config results correctly.
However performOCR not working at all and app is crashing every time i open the app.
Below is the log of android device.

06-09 12:37:33.631 12859-12859/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 12859 (.arttha.orcdemo)
06-09 12:37:33.683 322-322/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-09 12:37:33.683 322-322/? A/DEBUG: Build fingerprint: 'motorola/lux_retasia_ds/lux_uds:6.0.1/MPDS24.107-70-1-5/5:user/release-keys'
06-09 12:37:33.683 322-322/? A/DEBUG: Revision: 'p2c0'
06-09 12:37:33.683 322-322/? A/DEBUG: ABI: 'arm'
06-09 12:37:33.684 322-322/? A/DEBUG: pid: 12859, tid: 12859, name: .arttha.orcdemo  >>> com.arttha.orcdemo <<<
06-09 12:37:33.684 322-322/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
06-09 12:37:33.706 322-322/? A/DEBUG:     r0 00000000  r1 0000323b  r2 00000006  r3 b6f9eb7c
06-09 12:37:33.706 322-322/? A/DEBUG:     r4 b6f9eb84  r5 b6f9eb34  r6 00000054  r7 0000010c
06-09 12:37:33.706 322-322/? A/DEBUG:     r8 00000001  r9 b7f5e388  sl 00000000  fp b6d47a6c
06-09 12:37:33.707 322-322/? A/DEBUG:     ip 00000006  sp bed78ef0  lr b6d241cd  pc b6d265c8  cpsr 40010010
06-09 12:37:33.738 322-322/? A/DEBUG:     #00 pc 000445c8  /system/lib/libc.so (tgkill+12)
06-09 12:37:33.738 322-322/? A/DEBUG:     #01 pc 000421c9  /system/lib/libc.so (pthread_kill+32)
06-09 12:37:33.738 322-322/? A/DEBUG:     #02 pc 0001bb1f  /system/lib/libc.so (raise+10)
06-09 12:37:33.738 322-322/? A/DEBUG:     #03 pc 00018cc1  /system/lib/libc.so (__libc_android_abort+34)
06-09 12:37:33.738 322-322/? A/DEBUG:     #04 pc 00016880  /system/lib/libc.so (abort+4)
06-09 12:37:33.738 322-322/? A/DEBUG:     #05 pc 00042ba3  /data/app/com.arttha.orcdemo-1/lib/arm/libsap.so (_ZN9__gnu_cxx27__verbose_terminate_handlerEv+226)
06-09 12:37:33.738 322-322/? A/DEBUG:     #06 pc 0000ce2d  /data/app/com.arttha.orcdemo-1/lib/arm/libsap.so (_ZN10__cxxabiv111__terminateEPFvvE+4)
06-09 12:37:33.738 322-322/? A/DEBUG:     #07 pc 0000cea1  /data/app/com.arttha.orcdemo-1/lib/arm/libsap.so (_ZSt9terminatev+8)
06-09 12:37:33.738 322-322/? A/DEBUG:     #08 pc 0000b131  /data/app/com.arttha.orcdemo-1/lib/arm/libsap.so (_ZN3doo14LicenseManager25_installLicenseFromStringEPKcS2_+204)
06-09 12:37:33.738 322-322/? A/DEBUG:     #09 pc 0000bc15  /data/app/com.arttha.orcdemo-1/lib/arm/libsap.so (Java_io_scanbot_sap_SapManager_install+200)
06-09 12:37:33.738 322-322/? A/DEBUG:     #10 pc 00868991  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (void io.scanbot.sap.SapManager.install(java.lang.Object, byte[])+116)
06-09 12:37:33.738 322-322/? A/DEBUG:     #11 pc 00868f39  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (void io.scanbot.sap.SapManager.install(android.content.Context, byte[])+68)
06-09 12:37:33.738 322-322/? A/DEBUG:     #12 pc 008c4f17  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (io.scanbot.sap.SapManager net.doo.snap.c.c.b(android.content.Context)+690)
06-09 12:37:33.738 322-322/? A/DEBUG:     #13 pc 008c4be3  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (io.scanbot.sap.SapManager net.doo.snap.c.c.a(android.content.Context)+118)
06-09 12:37:33.738 322-322/? A/DEBUG:     #14 pc 008c46d7  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (io.scanbot.sap.SapManager net.doo.snap.c.a.a()+98)
06-09 12:37:33.738 322-322/? A/DEBUG:     #15 pc 008ba423  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (io.scanbot.sap.SapManager net.doo.snap.b.k.a(android.app.Application)+110)
06-09 12:37:33.738 322-322/? A/DEBUG:     #16 pc 008bfcd3  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (java.lang.Object net.doo.snap.b.w.get()+158)
06-09 12:37:33.739 322-322/? A/DEBUG:     #17 pc 0086458f  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (java.lang.Object dagger.internal.DoubleCheck.get()+162)
06-09 12:37:33.742 322-322/? A/DEBUG:     #18 pc 008b960b  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (io.scanbot.sap.SapManager net.doo.snap.b.j.b()+62)
06-09 12:37:33.742 322-322/? A/DEBUG:     #19 pc 008b0963  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (void net.doo.snap.ScanbotSDK.<init>(android.content.Context)+542)
06-09 12:37:33.742 322-322/? A/DEBUG:     #20 pc 008b06a5  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (void net.doo.snap.ScanbotSDK.<init>(android.app.Activity)+64)
06-09 12:37:33.742 322-322/? A/DEBUG:     #21 pc 0087dff5  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (void io.scanbot.sdk.plugin.cordova.ScanbotSdkWrapper$PdfSdk.<init>(android.app.Activity)+112)
06-09 12:37:33.742 322-322/? A/DEBUG:     #22 pc 00878389  /data/app/com.arttha.orcdemo-1/oat/arm/base.odex (offset 0x4c0000) (void io.scanbot.sdk.plugin.cordova.ScanbotSdkPlugin$1.run()+124)
06-09 12:37:33.742 322-322/? A/DEBUG:     #23 pc 028002ef  /system/framework/arm/boot.oat (offset 0x2018000)
06-09 12:37:34.549 1935-12919/? W/ActivityManager:   Force finishing activity com.arttha.orcdemo/.MainActivity
06-09 12:37:34.553 322-322/? E/DEBUG: AM write failed: Broken pipe
06-09 12:37:34.555 1935-2047/? I/BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
06-09 12:37:34.596 1935-12919/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 104)
06-09 12:37:34.597 1935-12919/? W/ActivityManager: Exception thrown during pause
                                                   android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
                                                       at android.os.BinderProxy.transactNative(Native Method)
                                                       at android.os.BinderProxy.transact(Binder.java:503)
                                                       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:734)
                                                       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:866)
                                                       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2928)
                                                       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2784)
                                                       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2801)
                                                       at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12297)
                                                       at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:12193)
                                                       at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12910)
                                                       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12395)
                                                       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

Please help to resolve this issue as it's happening on every android device.

Thanks,
Jitendra

**Comment by eddyfrank** [comment]
Hi Jitendra,

thanks for the input. 

I cannot reproduce such errors with our test apps and I don't see any issues with the Scanbot SDK Plugin. 
Could you please contact our SDK Team via sdk@scanbot.io 
Thanks.

Regards,
Eddy

**Comment by phonegap20** [comment]
Hi Jitendra,

Thanks for quick response.
can you provide me test apk file to test that at end ?

Regards,
Eddy
